CREATE TABLE IF NOT EXISTS  VOTE(
    ID UUID PRIMARY KEY,
    ID_SESSION UUID NOT NULL,
    VOTED_BY UUID NOT NULL,
    VOTE CHAR(3) NOT NULL,
    CONSTRAINT fk_voted_by_member_vote FOREIGN KEY (VOTED_BY) REFERENCES MEMBER(ID),
    CONSTRAINT fk_session_vote FOREIGN KEY (ID_SESSION) REFERENCES VOTING_SESSION(ID)
);