CREATE TABLE IF NOT EXISTS VOTE(
    ID UUID PRIMARY KEY,
    ID_SESSION UUID NOT NULL,
    VOTED_BY VARCHAR(36) NOT NULL,
    VOTE CHAR(3) NOT NULL,
    CONSTRAINT fk_voted_by_member_vote FOREIGN KEY (VOTED_BY) REFERENCES KEYCLOAK.USER_ENTITY(ID),
    CONSTRAINT fk_session_vote FOREIGN KEY (ID_SESSION) REFERENCES VOTING_SESSION(ID)
);