CREATE TABLE IF NOT EXISTS LAST_CONSULTED_SESSIONS(
    ID UUID PRIMARY KEY,
    ID_SESSION UUID NOT NULL,
    ID_VIEWER VARCHAR(36) NOT NULL,
    CONSULT_HOUR TIMESTAMP NOT NULL,
    CONSTRAINT fk_id_viewer_consulted FOREIGN KEY (ID_VIEWER) REFERENCES KEYCLOAK.USER_ENTITY(ID),
    CONSTRAINT fk_id_session_consulted FOREIGN KEY (ID_SESSION) REFERENCES VOTING.VOTING_SESSION(ID),
    UNIQUE (ID_SESSION, ID_VIEWER)
);