spring:
  flyway:
    schemas: voting
    locations: classpath:migration-test, classpath:db/migration
    cloud:
      config:
        enabled: false
      discovery:
        enabled: false
  aot:
    enabled: false
