name: Test

on:
  push:
    branches: ['main']
      
jobs:
  build:
    name: Server Test
    runs-on: ubuntu-latest
    steps: 
     - uses: actions/checkout@v3
     - name: Install Java 17
       uses: actions/setup-java@v3
       with:
         java-version: 17
         distribution: 'temurin'
         cache: 'gradle'
     - name: Run Test
       working-directory: ./server
       run: gradle build
  web:
     name: Web Test
     runs-on: ubuntu-latest
     strategy:
      matrix:
        node-version: [18.x]
     steps: 
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
         node-version: ${{ matrix.node-version }}
      - name: Install modules
        working-directory: ./web
        run: npm install --force
      - name: Run test
        working-directory: ./web
        run: npm run test.ci
        env:
         CI: true	
       
